import subprocess
import numpy as np


TRUE_COEFFS = [0.5, -0.3]
TRUE_AMPLITUDE = 1.0
LENGTH = 20000
TRANSIENTS = 2000


def run_ar_run(coeff_file):
    result = subprocess.run(
        [
            "./bin/ar-run",
            f"-l{LENGTH}",
            f"-p{len(TRUE_COEFFS)}",
            f"-x{TRANSIENTS}",
            "-I1",
            str(coeff_file),
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def run_ar_model(data_file):
    result = subprocess.run(
        ["./bin/ar-model", "-m1", f"-p{len(TRUE_COEFFS)}", str(data_file)],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def parse_coefficients(text):
    # ar-model prints each fitted coefficient on its own "# <value>" line.
    coeffs = []
    for line in text.splitlines():
        parts = line.strip().split()
        if len(parts) == 2 and parts[0] == "#":
            try:
                coeffs.append(float(parts[1]))
            except ValueError:
                continue
    return np.array(coeffs)


def test_ar_run_generates_data_ar_model_can_recover(tmp_path):
    # ar-run.c uses the C rand/gaussian routines, which produce a different
    # sequence than the original Fortran rgauss. So its raw output can't be
    # compared byte for byte against a reference generated by the Fortran
    # binary. Instead, generate a series from known AR coefficients and
    # check that ar-model, fitted on that series, recovers coefficients
    # close to the true ones.
    coeff_file = tmp_path / "coeffs.txt"
    coeff_file.write_text(
        f"{TRUE_AMPLITUDE}\n" + "\n".join(str(c) for c in TRUE_COEFFS) + "\n"
    )

    series = run_ar_run(coeff_file)
    assert len(series.splitlines()) == LENGTH

    data_file = tmp_path / "ar-run_out.txt"
    data_file.write_text(series)

    fitted = run_ar_model(data_file)
    coeffs = parse_coefficients(fitted)

    assert len(coeffs) == len(TRUE_COEFFS)
    np.testing.assert_allclose(coeffs, TRUE_COEFFS, atol=0.05)
